name: Sync Google Sheets to Supabase

on:
  # Schedule to run every day at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      force_sync:
        description: 'Force sync even if no changes detected'
        required: false
        default: 'false'
        type: boolean

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
      - name: Install dependencies
      run: |
        npm install --omit=dev
        npm install googleapis @supabase/supabase-js
        npm audit fix --force
    
    - name: Run sync script
      env:
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        GOOGLE_SHEETS_ID_2025: ${{ secrets.GOOGLE_SHEETS_ID_2025 }}
        GOOGLE_SHEETS_ID_INVOICE: ${{ secrets.GOOGLE_SHEETS_ID_INVOICE }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      run: |
        echo "Starting sync process..."
        node scripts/sync-sheets.js
        echo "Sync completed!"
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Sync failed! Check the logs above for details."
        echo "Please check your environment variables and Google Sheets access."
