name: Smart Sync Google Sheets to Supabase

on:
  # Schedule to run every 4 hours
  #schedule:
    #- cron: '0 */4 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      sync_method:
        description: 'Sync method to use'
        required: false
        default: 'smart'
        type: choice
        options:
        - smart
        - optimized
        - original

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install --omit=dev
        npm install googleapis @supabase/supabase-js
        
    - name: Run sync
      env:
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        GOOGLE_SHEETS_ID_2025: ${{ secrets.GOOGLE_SHEETS_ID_2025 }}
        GOOGLE_SHEETS_ID_INVOICE: ${{ secrets.GOOGLE_SHEETS_ID_INVOICE }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      run: |
        METHOD="${{ github.event.inputs.sync_method || 'smart' }}"
        echo "🚀 Running sync with method: $METHOD"
        node scripts/sync-smart.js $METHOD
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Sync process failed!"
        echo "Please check the logs and verify environment variables."
        echo "❌ Sync failed! Check the logs above for details."
        echo "Please check your environment variables and Google Sheets access."
